version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      # Esto sincroniza el código local con el contenedor para que no se
      # tenga que reconstruir la imagen cada vez que cambiamos algo en app.py
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=${DATABASE_URL}