version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      # Esto sincroniza tu código local con el contenedor para que no 
      # tengas que reconstruir la imagen cada vez que cambias algo en app.py
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1